CREATE DATABASE ENCUESTAUTC
GO

USE ENCUESTAUTC
GO

CREATE TABLE PARTIDO
(
IDPartido INT IDENTITY(1,1),
NOMBRE VARCHAR(50)
CONSTRAINT pk_IDPartido PRIMARY KEY(IDPartido)
)

CREATE TABLE ENCUESTA
(
NumeroEncuesta INT IDENTITY(1,1),
NombreParticipante VARCHAR(50),
Edad INT,
Correo VARCHAR(50),
PartidoPolitico INT,
CONSTRAINT pk_NumeroEncuesta PRIMARY KEY(NumeroEncuesta),
CONSTRAINT UQ_CORREO UNIQUE (CORREO) 
)
SELECT * FROM ENCUESTA

INSERT INTO PARTIDO(NOMBRE) VALUES
('PLN'), ('PUSC'), ('PAC'), ('PNG'), ('PASE'), ('PIN')

SELECT * FROM PARTIDO

CREATE PROCEDURE AGREGAR_ENCUESTA
@NOMBRE VARCHAR(50),
@EDAD INT,
@CORREO VARCHAR(50),
@PARTIDO INT
AS
	BEGIN
	INSERT INTO ENCUESTA(NombreParticipante, Edad, Correo, PartidoPolitico) VALUES (@NOMBRE, @EDAD, @CORREO, @PARTIDO)
	END

CREATE PROCEDURE CONSULTAR_FORMULARIOS
AS
	BEGIN
	SELECT ENCUESTA.NumeroEncuesta, ENCUESTA.NombreParticipante as Nombre, ENCUESTA.Edad as Edad, ENCUESTA.Correo as Correo, ENCUESTA.PartidoPolitico as Partido FROM ENCUESTA
	INNER JOIN PARTIDO ON ENCUESTA.PartidoPolitico = PARTIDO.IDPartido
	END

CREATE PROCEDURE CONSULTA_PARTIDO
AS
	BEGIN
	SELECT IDPartido, NOMBRE FROM PARTIDO
	END